osx_image: xcode10.1
language: swift

#xcode_project: ./CoreDataPref/CoreDataPref.xcodeproj # path to your xcodeproj folder

script:
- cd ./CoreDataPref
- xcodebuild -list -workspace ./CoreDataDefaults.xcworkspace
- xcodebuild clean build -workspace ./CoreDataDefaults.xcworkspace -scheme CoreDataDefaults -sdk iphonesimulator12.1
- xcodebuild test -workspace ./CoreDataDefaults.xcworkspace -scheme CoreDataDefaults -sdk iphonesimulator12.1
