osx_image: xcode7.3
language: objective-c

before_install:
- brew update
- if brew outdated | grep -qx carthage; then brew upgrade carthage; fi
- travis_wait 35 carthage bootstrap --platform iOS,Mac

script:
- xcodebuild clean build -project CoreDataPref.xcodeproj -scheme CoreDataPref -sdk iphonesimulator
- xcodebuild test -project CoreDataPref.xcodeproj -scheme CoreDataPref -sdk iphonesimulator
- xcodebuild clean build -project CoreDataPrefSample.xcodeproj -scheme CoreDataPrefSample -sdk iphonesimulator
