osx_image: xcode10.1
language: swift

xcode_project: ./CoreDataPref/CoreDataPref.xcodeproj # path to your xcodeproj folder
xcode_scheme: CoreDataPrefTests
xcode_destination: platform=iOS Simulator,OS=10.1,name=iPhone XS


script:
- xcodebuild clean build -project CoreDataPref.xcodeproj -scheme CoreDataPref -sdk iphonesimulator
- xcodebuild test -project CoreDataPref.xcodeproj -scheme CoreDataPref -sdk iphonesimulator
- xcodebuild clean build -project CoreDataPrefSample.xcodeproj -scheme CoreDataPrefSample -sdk iphonesimulator
