# Uncomment the next line to define a global platform for your project
 platform :ios, '8.4'

# ignore all warnings from all dependencies
inhibit_all_warnings!

target 'CoreDataPref' do
    # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
    use_frameworks!

    # Pods for CoreDataPref
    pod 'EncryptedCoreData'

    target 'CoreDataPrefTests' do
        inherit! :search_paths
        # Pods for testing
    end

end

target 'CoreDataPrefPackageDescription' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CoreDataPrefPackageDescription

end
